import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import NextAuthSessionProvider from "./provider";
import { Toaster } from "@/components/ui/sonner";

const inter = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Shmookies - Discover and reserve the best restaurants",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#F4ECE1]`}>
        <NextAuthSessionProvider>
          <div className="mx-6 md:mx-16 ">
            <Header />
            <Toaster />
            {children}
          </div>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
